name: KitPvPPlus
#Remeber to update it in the pom
version: 1.0
main: wtf.nucker.kitpvpplus.KitPvPPlus
load: POSTWORLD
authors: [Nucker]
description: Customizable kitpvp core for 1.8-1.16
website: nucker.me
api-version: 1.13
loadbefore:
  - Essentials
softdepend:
  - PlaceholderAPI
  - Vault
  - WorldGuard